// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCAnimationFrame : CCObject  {
    void setSpriteFrame(any arg0);
    [CallWith=ScriptState] any getUserInfo();
    void setDelayUnits(float arg0);
    [CallWith=ScriptState] any getSpriteFrame();
    float getDelayUnits();
    void setUserInfoWithDictionary(CCDictionary arg0);
    boolean initWithSpriteFrameWithDictionary(any arg0, float arg1, CCDictionary arg2);
};
