// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCCardinalSplineTo : CCActionInterval {
    void startWithTarget(any arg0);
    [CallWith=ScriptState] any reverse();
    boolean initWithDuration(float arg0, any[] arg1, float arg2);
    [CallWith=ScriptState] any getPoints();
    void update(float arg0);
    void updatePosition(CCPoint arg0);
};
