// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCGLNode : CCNode  {

    void setDrawCallback(OnDrawCallback callback);
    [Custom] void ctor();
};
