// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCTableView : CCScrollView {
    void setVerticalFillOrder(short arg0);
    void scrollViewDidScroll(CCScrollView arg0);
    void updateCellAtIndex(unsigned long arg0);
    boolean initWithViewSize(CCSize arg0, any arg1);
    void removeCellAtIndex(unsigned long arg0);
    void reloadData();
    CCTableViewCell dequeueCell();
    short getVerticalFillOrder();
    void scrollViewDidZoom(CCScrollView arg0);
    void insertCellAtIndex(unsigned long arg0);
    CCTableViewCell cellAtIndex(unsigned long arg0);
    void updateContentSize();
    void setDelegateInternal(ScrollViewCallback didScrollCallback,
        ScrollViewCallback didZoomCallback,
        TableViewCallback touchedCallback,
        TableViewCallback highlightCallback,
        TableViewCallback unhighlightCallback,
        TableViewCallback willrecycleCallback
        );
    void setDataSourceInternal(TableCellSizeForIndexCallback sizeForIndex,
        TableNumberOfCellsCallback numberOfCells,
        TableCellAtIndexCallback cellAtIndex);
    void setCellSizeInternal(CCSize size);
    void setNumberOfCellsInternal(long size);
    void setCurrentCellInternal(any cell);
};
