// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    NoInterfaceObject
] interface CCObject {
    void retain();
    void release();
    [CallWith=ScriptState] any copy();
    [CallWith=ScriptState] any clone();
    void autorelease();
    readonly attribute long instanceId;
};
