// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    GarbageCollected,
    NoInterfaceObject
] interface Cocos2d {
    void setContext(WebGLRenderingContext context);
    void glEnableVertexAttribs(unsigned long flags);
    
    [Custom=Getter] readonly attribute CCDrawNode DrawNode;
    [Custom=Getter] readonly attribute CCScrollView ScrollView;
    [Custom=Getter] readonly attribute CCEaseSineIn EaseSineIn;
    [Custom=Getter] readonly attribute CCProgressTo ProgressTo;
    [Custom=Getter] readonly attribute CCHide Hide;
    [Custom=Getter] readonly attribute CCTransitionMoveInB TransitionMoveInB;
    [Custom=Getter] readonly attribute CCTransitionMoveInL TransitionMoveInL;
    [Custom=Getter] readonly attribute CCEGLView EGLView;
    [Custom=Getter] readonly attribute CCTransitionMoveInR TransitionMoveInR;
    [Custom=Getter] readonly attribute CCScheduler Scheduler;
    [Custom=Getter] readonly attribute CCParticleSystemQuad ParticleSystem;
    [Custom=Getter] readonly attribute CCParticleFlower ParticleFlower;
    [Custom=Getter] readonly attribute CCParticleGalaxy ParticleGalaxy;
    [Custom=Getter] readonly attribute CCParticleMeteor ParticleMeteor;
    [Custom=Getter] readonly attribute CCParticleSpiral ParticleSpiral;
    [Custom=Getter] readonly attribute CCParticleExplosion ParticleExplosion;
    [Custom=Getter] readonly attribute CCParticleSmoke ParticleSmoke;
    [Custom=Getter] readonly attribute CCParticleSnow ParticleSnow;
    [Custom=Getter] readonly attribute CCParticleRain ParticleRain;
    [Custom=Getter] readonly attribute CCParticleSun ParticleSun;
    [Custom=Getter] readonly attribute CCParticleFire ParticleFire;
    [Custom=Getter] readonly attribute CCParticleFireworks ParticleFireworks;
    [Custom=Getter] readonly attribute CCTransitionProgressHorizontal TransitionProgressHorizontal;
    [Custom=Getter] readonly attribute CCMoveTo MoveTo;
    [Custom=Getter] readonly attribute CCJumpBy JumpBy;
    [Custom=Getter] readonly attribute CCAnimationFrame AnimationFrame;
    [Custom=Getter] readonly attribute CCEaseBounceIn EaseBounceIn;
    [Custom=Getter] readonly attribute CCTransitionRotoZoom TransitionRotoZoom;
    [Custom=Getter] readonly attribute CCDirector Director;
    [Custom=Getter] readonly attribute CCTexture2D Texture2D;
    [Custom=Getter] readonly attribute CCEaseElasticOut EaseElasticOut;
    [Custom=Getter] readonly attribute CCEaseBackOut EaseBackOut;
    [Custom=Getter] readonly attribute CCTransitionFlipX TransitionFlipX;
    [Custom=Getter] readonly attribute CCStopGrid StopGrid;
    [Custom=Getter] readonly attribute CCTransitionScene TransitionScene;
    [Custom=Getter] readonly attribute CCSkewBy SkewBy;
    [Custom=Getter] readonly attribute CCTransitionProgressVertical TransitionProgressVertical;
    [Custom=Getter] readonly attribute CCLayer Layer;
    [Custom=Getter] readonly attribute CCEaseElastic EaseElastic;
    [Custom=Getter] readonly attribute CCGrid3DAction Grid3DAction;
    [Custom=Getter] readonly attribute CCFadeIn FadeIn;
    [Custom=Getter] readonly attribute CCNodeRGBA NodeRGBA;
    [Custom=Getter] readonly attribute CCAnimationCache AnimationCache;
    [Custom=Getter] readonly attribute CCFlipY3D FlipY3D;
    [Custom=Getter] readonly attribute CCEaseSineInOut EaseSineInOut;
    [Custom=Getter] readonly attribute CCTransitionFlipAngular TransitionFlipAngular;
    [Custom=Getter] readonly attribute CCTransitionMoveInT TransitionMoveInT;
    [Custom=Getter] readonly attribute CCEaseElasticInOut EaseElasticInOut;
    [Custom=Getter] readonly attribute CCEaseBounce EaseBounce;
    [Custom=Getter] readonly attribute CCShow Show;
    [Custom=Getter] readonly attribute CCFadeOut FadeOut;
    [Custom=Getter] readonly attribute CCCallFunc CallFunc;
    [Custom=Getter] readonly attribute CCWaves3D Waves3D;
    [Custom=Getter] readonly attribute CCTouch Touch;
    [Custom=Getter] readonly attribute CCMenuItemImage MenuItemImage;
    [Custom=Getter] readonly attribute CCMenuItem MenuItem;
    [Custom=Getter] readonly attribute CCActionEase ActionEase;
    [Custom=Getter] readonly attribute CCTransitionSceneOriented TransitionSceneOriented;
    [Custom=Getter] readonly attribute CCTransitionZoomFlipAngular TransitionZoomFlipAngular;
    [Custom=Getter] readonly attribute CCEaseIn EaseIn;
    [Custom=Getter] readonly attribute CCEaseExponentialInOut EaseExponentialInOut;
    [Custom=Getter] readonly attribute CCEaseBackInOut EaseBackInOut;
    [Custom=Getter] readonly attribute CCEaseExponentialOut EaseExponentialOut;
    [Custom=Getter] readonly attribute CCFlipX3D FlipX3D;
    [Custom=Getter] readonly attribute CCDelayTime DelayTime;
    [Custom=Getter] readonly attribute CCProgressTimer ProgressTimer;
    [Custom=Getter] readonly attribute CCLabelBMFont LabelBMFont;
    [Custom=Getter] readonly attribute CCTransitionFadeBL TransitionFadeBL;
    [Custom=Getter] readonly attribute CCEaseElasticIn EaseElasticIn;
    [Custom=Getter] readonly attribute CCTransitionFadeTR TransitionFadeTR;
    [Custom=Getter] readonly attribute CCFiniteTimeAction FiniteTimeAction;
    [Custom=Getter] readonly attribute CCFadeOutDownTiles FadeOutDownTiles;
    [Custom=Getter] readonly attribute CCJumpTiles3D JumpTiles3D;
    [Custom=Getter] readonly attribute CCEaseBackIn EaseBackIn;
    [Custom=Getter] readonly attribute CCSpriteBatchNode SpriteBatchNode;
    [Custom=Getter] readonly attribute CCActionCamera ActionCamera;
    [Custom=Getter] readonly attribute CCActionTween ActionTween;
    [Custom=Getter] readonly attribute CCTransitionFadeDown TransitionFadeDown;
    [Custom=Getter] readonly attribute CCProgressFromTo ProgressFromTo;
    [Custom=Getter] readonly attribute CCActionManager ActionManager;
    [Custom=Getter] readonly attribute CCFlipX FlipX;
    [Custom=Getter] readonly attribute CCFlipY FlipY;
    [Custom=Getter] readonly attribute CCTransitionSplitCols TransitionSplitCols;
    [Custom=Getter] readonly attribute CCTimer Timer;
    [Custom=Getter] readonly attribute CCFadeTo FadeTo;
    [Custom=Getter] readonly attribute CCRepeatForever RepeatForever;
    [Custom=Getter] readonly attribute CCPlace Place;
    [Custom=Getter] readonly attribute CCTiledGrid3D TiledGrid3D;
    [Custom=Getter] readonly attribute CCMenuItemLabel MenuItemLabel;
    [Custom=Getter] readonly attribute CCRenderTexture RenderTexture;
    [Custom=Getter] readonly attribute CCAnimate Animate;
    [Custom=Getter] readonly attribute CCTransitionShrinkGrow TransitionShrinkGrow;
    [Custom=Getter] readonly attribute CCLabelTTF LabelTTF;
    [Custom=Getter] readonly attribute CCLayerMultiplex LayerMultiplex;
    [Custom=Getter] readonly attribute CCBlink Blink;
    [Custom=Getter] readonly attribute CCShaderCache ShaderCache;
    [Custom=Getter] readonly attribute CCJumpTo JumpTo;
    [Custom=Getter] readonly attribute CCAtlasNode AtlasNode;
    [Custom=Getter] readonly attribute CCTransitionJumpZoom TransitionJumpZoom;
    [Custom=Getter] readonly attribute CCSpriteFrameCache SpriteFrameCache;
    [Custom=Getter] readonly attribute CCCatmullRomBy CatmullRomBy;
    [Custom=Getter] readonly attribute CCTiledGrid3DAction TiledGrid3DAction;
    [Custom=Getter] readonly attribute CCGLProgram GLProgram;
    [Custom=Getter] readonly attribute CCTwirl Twirl;
    [Custom=Getter] readonly attribute CCLayerColor LayerColor;
    [Custom=Getter] readonly attribute CCFadeOutBLTiles FadeOutBLTiles;
    [Custom=Getter] readonly attribute CCTransitionProgress TransitionProgress;
    [Custom=Getter] readonly attribute CCEaseRateAction EaseRateAction;
    [Custom=Getter] readonly attribute CCLayerGradient LayerGradient;
    [Custom=Getter] readonly attribute CCMenuItemSprite MenuItemSprite;
    [Custom=Getter] readonly attribute CCNode Node;
    [Custom=Getter] readonly attribute CCGLNode GLNode;
    [Custom=Getter] readonly attribute CCToggleVisibility ToggleVisibility;
    [Custom=Getter] readonly attribute CCRepeat Repeat;
    [Custom=Getter] readonly attribute CCCardinalSplineBy CardinalSplineBy;
    [Custom=Getter] readonly attribute CCTransitionFlipY TransitionFlipY;
    [Custom=Getter] readonly attribute CCTurnOffTiles TurnOffTiles;
    [Custom=Getter] readonly attribute CCTintTo TintTo;
    [Custom=Getter] readonly attribute CCCatmullRomTo CatmullRomTo;
    [Custom=Getter] readonly attribute CCActionInstant ActionInstant;
    [Custom=Getter] readonly attribute CCTargetedAction TargetedAction;
    [Custom=Getter] readonly attribute CCTransitionTurnOffTiles TransitionTurnOffTiles;
    [Custom=Getter] readonly attribute CCRotateTo RotateTo;
    [Custom=Getter] readonly attribute CCTransitionSplitRows TransitionSplitRows;
    [Custom=Getter] readonly attribute CCTransitionProgressRadialCCW TransitionProgressRadialCCW;
    [Custom=Getter] readonly attribute CCScaleTo ScaleTo;
    [Custom=Getter] readonly attribute CCTransitionPageTurn TransitionPageTurn;
    [Custom=Getter] readonly attribute CCSplitRows SplitRows;
    [Custom=Getter] readonly attribute CCSpriteFrame SpriteFrame;
    [Custom=Getter] readonly attribute CCLiquid Liquid;
    [Custom=Getter] readonly attribute CCParticleBatchNode ParticleBatchNode;
    [Custom=Getter] readonly attribute CCTransitionZoomFlipX TransitionZoomFlipX;
    [Custom=Getter] readonly attribute CCTransitionCrossFade TransitionCrossFade;
    [Custom=Getter] readonly attribute CCRipple3D Ripple3D;
    [Custom=Getter] readonly attribute CCAction Action;
    [Custom=Getter] readonly attribute CCGridBase GridBase;
    [Custom=Getter] readonly attribute CCAnimation Animation;
    [Custom=Getter] readonly attribute CCSpawn Spawn;
    [Custom=Getter] readonly attribute CCSet Set;
    [Custom=Getter] readonly attribute CCShakyTiles3D ShakyTiles3D;
    [Custom=Getter] readonly attribute CCPageTurn3D PageTurn3D;
    [Custom=Getter] readonly attribute CCGrid3D Grid3D;
    [Custom=Getter] readonly attribute CCTransitionProgressInOut TransitionProgressInOut;
    [Custom=Getter] readonly attribute CCTransitionFadeUp TransitionFadeUp;
    [Custom=Getter] readonly attribute CCCamera Camera;
    [Custom=Getter] readonly attribute CCLayerRGBA LayerRGBA;
    [Custom=Getter] readonly attribute CCBezierTo BezierTo;
    [Custom=Getter] readonly attribute CCFollow Follow;
    [Custom=Getter] readonly attribute CCTintBy TintBy;
    [Custom=Getter] readonly attribute CCActionInterval ActionInterval;
    [Custom=Getter] readonly attribute CCEaseBounceInOut EaseBounceInOut;
    [Custom=Getter] readonly attribute CCMenu Menu;
    [Custom=Getter] readonly attribute CCEaseInOut EaseInOut;
    [Custom=Getter] readonly attribute CCTransitionZoomFlipY TransitionZoomFlipY;
    [Custom=Getter] readonly attribute CCScaleBy ScaleBy;
    [Custom=Getter] readonly attribute CCLens3D Lens3D;
    [Custom=Getter] readonly attribute CCSkewTo SkewTo;
    [Custom=Getter] readonly attribute CCCardinalSplineTo CardinalSplineTo;
    [Custom=Getter] readonly attribute CCEaseExponentialIn EaseExponentialIn;
    [Custom=Getter] readonly attribute CCReuseGrid ReuseGrid;
    [Custom=Getter] readonly attribute CCMenuItemAtlasFont MenuItemAtlasFont;
    [Custom=Getter] readonly attribute CCSprite Sprite;
    [Custom=Getter] readonly attribute CCOrbitCamera OrbitCamera;
    [Custom=Getter] readonly attribute CCComponent Component;
    [Custom=Getter] readonly attribute CCFadeOutUpTiles FadeOutUpTiles;
    [Custom=Getter] readonly attribute CCTextFieldTTF TextFieldTTF;
    [Custom=Getter] readonly attribute CCWaves Waves;
    [Custom=Getter] readonly attribute CCEaseOut EaseOut;
    [Custom=Getter] readonly attribute CCMenuItemFont MenuItemFont;
    [Custom=Getter] readonly attribute CCEaseSineOut EaseSineOut;
    [Custom=Getter] readonly attribute CCTextureCache TextureCache;
    [Custom=Getter] readonly attribute CCMenuItemToggle MenuItemToggle;
    [Custom=Getter] readonly attribute CCSplitCols SplitCols;
    [Custom=Getter] readonly attribute CCEGLViewProtocol EGLViewProtocol;
    [Custom=Getter] readonly attribute CCMoveBy MoveBy;
    [Custom=Getter] readonly attribute CCMotionStreak MotionStreak;
    [Custom=Getter] readonly attribute CCRotateBy RotateBy;
    [Custom=Getter] readonly attribute CCBezierBy BezierBy;
    [Custom=Getter] readonly attribute CCFadeOutTRTiles FadeOutTRTiles;
    [Custom=Getter] readonly attribute CCScene Scene;
    [Custom=Getter] readonly attribute CCTransitionFade TransitionFade;
    [Custom=Getter] readonly attribute CCTransitionProgressOutIn TransitionProgressOutIn;
    [Custom=Getter] readonly attribute CCEaseBounceOut EaseBounceOut;
    [Custom=Getter] readonly attribute CCGridAction GridAction;
    [Custom=Getter] readonly attribute CCSequence Sequence;
    [Custom=Getter] readonly attribute CCShaky3D Shaky3D;
    [Custom=Getter] readonly attribute CCTransitionProgressRadialCW TransitionProgressRadialCW;
    [Custom=Getter] readonly attribute CCShuffleTiles ShuffleTiles;
    [Custom=Getter] readonly attribute CCTransitionSlideInR TransitionSlideInR;
    [Custom=Getter] readonly attribute CCTransitionSlideInT TransitionSlideInT;
    [Custom=Getter] readonly attribute CCTransitionSlideInL TransitionSlideInL;
    [Custom=Getter] readonly attribute CCWavesTiles3D WavesTiles3D;
    [Custom=Getter] readonly attribute CCTransitionSlideInB TransitionSlideInB;
    [Custom=Getter] readonly attribute CCSpeed Speed;
    [Custom=Getter] readonly attribute CCShatteredTiles3D ShatteredTiles3D;
    [Custom=Getter] readonly attribute CCTMXLayer TMXLayer;
    [Custom=Getter] readonly attribute CCTMXLayerInfo TMXLayerInfo;
    [Custom=Getter] readonly attribute CCTMXMapInfo TMXMapInfo;
    [Custom=Getter] readonly attribute CCTMXObjectGroup TMXObjectGroup;
    [Custom=Getter] readonly attribute CCTMXTiledMap TMXTiledMap;
    [Custom=Getter] readonly attribute CCTMXTilesetInfo TMXTilesetInfo;
    [Custom=Getter] readonly attribute CCLabelAtlas LabelAtlas;
    [Custom=Getter] readonly attribute CCScale9Sprite Scale9Sprite;
    [Custom=Getter] readonly attribute CCArmature Armature;
    [Custom=Getter] readonly attribute CCArmatureAnimation ArmatureAnimation;
    [Custom=Getter] readonly attribute CCArmatureDataManager ArmatureDataManager;
    [Custom=Getter] readonly attribute CCTouchDelegate TouchDelegate;
    [Custom=Getter] readonly attribute CCDictionary Dictionary;
    [Custom=Getter] readonly attribute CCPoint Point;
    [Custom=Getter] readonly attribute CCArray Array;
    [Custom=Getter] readonly attribute CCAffineTransform AffineTransform;
    [Custom=Getter] readonly attribute CCRect Rect;
    [Custom=Getter] readonly attribute CCSize Size;
    [Custom=Getter] readonly attribute ccColor3B Color3B;
    [Custom=Getter] readonly attribute ccColor4B Color4B;
    [Custom=Getter] readonly attribute ccColor4F Color4F;
    [Custom=Getter] readonly attribute CCClippingNode ClippingNode;
    [Custom=Getter] readonly attribute CCTableViewCell TableViewCell;
    [Custom=Getter] readonly attribute CCComController ComController;
    [Custom=Getter] readonly attribute CCTableView TableView;
    void forceGC();
};
