// Copyright (C) 2015 Intel Inc. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=WEBCL,
] interface WebCLGLObjectInfo {
    [CallWith=ScriptState] readonly attribute any glObject;
    [CallWith=ScriptState] readonly attribute any type;
    [CallWith=ScriptState] readonly attribute any textureTarget;
    [CallWith=ScriptState] readonly attribute any mipmapLevel;
};
