// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface ActionObject : CCObject  {
    void setCurrentTime(float arg0);
    void pause();
    void setName(DOMString arg0);
    void setUnitTime(float arg0);
    float getTotalTime();
    DOMString getName();
    void stop();
    void play(CCCallFunc arg0);
    void play();
    float getCurrentTime();
    void removeActionNode(Uint8Array arg0);
    boolean getLoop();
    void addActionNode(Uint8Array arg0);
    float getUnitTime();
    boolean isPlaying();
    void updateToFrameByTime(float arg0);
    void setLoop(boolean arg0);
    void simulationActionUpdate(float arg0);
};
