// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCAnimationCache : CCObject  {
    [CallWith=ScriptState] any getAnimation(DOMString arg0);
    void addAnimations(DOMString arg0);
    boolean init();
    void addAnimationsWithDictionary(CCDictionary arg0, DOMString arg1);
    void removeAnimation(DOMString arg0);
    void addAnimation(CCAnimation arg0, DOMString arg1);
     static void purgeSharedAnimationCache();
    [CallWith=ScriptState]  static any getInstance();
};
