// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCAtlasNode : CCNodeRGBA {
    void setTexture(CCTexture2D arg0);
    void draw();
    boolean initWithTileFile(DOMString arg0, unsigned long arg1, unsigned long arg2, unsigned long arg3);
    void setColor(ccColor3B arg0);
    void setOpacity(unsigned short arg0);
    [CallWith=ScriptState] any getTexture();
    void setOpacityModifyRGB(boolean arg0);
    unsigned long getQuadsToDraw();
    void updateAtlasValues();
    ccColor3B getColor();
    boolean initWithTexture(CCTexture2D arg0, unsigned long arg1, unsigned long arg2, unsigned long arg3);
    boolean isOpacityModifyRGB();
    void setQuadsToDraw(unsigned long arg0);
    [CallWith=ScriptState]  static any createInternal(DOMString arg0, unsigned long arg1, unsigned long arg2, unsigned long arg3);
};
