// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCComponent : CCObject  {
    void setEnabled(boolean arg0);
    void setName(DOMString arg0);
    boolean isEnabled();
    void update(float arg0);
    [CallWith=ScriptState] any getOwner();
    boolean init();
    void setOwner(any arg0);
    DOMString getName();
    [CallWith=ScriptState]  static any createInternal();
};
