// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCControlSaturationBrightnessPicker : CCControl {
    [CallWith=ScriptState] any getShadow();
    boolean initWithTargetAndPos(CCNode arg0, CCPoint arg1);
    CCPoint getStartPos();
    [CallWith=ScriptState] any getOverlay();
    void setEnabled(boolean arg0);
    [CallWith=ScriptState] any getSlider();
    [CallWith=ScriptState] any getBackground();
    float getSaturation();
    float getBrightness();
    [CallWith=ScriptState]  static any createInternal(CCNode arg0, CCPoint arg1);
};
