// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCControlStepper : CCControl {
    void setMinusSprite(CCSprite arg0);
    [CallWith=ScriptState] any getMinusLabel();
    void setWraps(boolean arg0);
    boolean isContinuous();
    [CallWith=ScriptState] any getMinusSprite();
    void updateLayoutUsingTouchLocation(CCPoint arg0);
    void setValueWithSendingEvent(double arg0, boolean arg1);
    [CallWith=ScriptState] any getPlusLabel();
    void stopAutorepeat();
    void setMaximumValue(double arg0);
    void setPlusSprite(CCSprite arg0);
    void setMinusLabel(CCLabelTTF arg0);
    void setValue(double arg0);
    void setStepValue(double arg0);
    [CallWith=ScriptState] any getPlusSprite();
    void update(float arg0);
    void setMinimumValue(double arg0);
    void startAutorepeat();
    boolean initWithMinusSpriteAndPlusSprite(CCSprite arg0, CCSprite arg1);
    double getValue();
    void setPlusLabel(CCLabelTTF arg0);
    [CallWith=ScriptState]  static any createInternal(CCSprite arg0, CCSprite arg1);
};
