// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCInputDelegate : CCObject  {
    boolean isAccelerometerEnabled();
    void setKeypadEnabled(boolean arg0);
    long getTouchMode();
    void setAccelerometerEnabled(boolean arg0);
    boolean isKeypadEnabled();
    boolean isTouchEnabled();
    void setTouchPriority(long arg0);
    long getTouchPriority();
    void setTouchEnabled(boolean arg0);
    void setTouchMode(short arg0);
};
