// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCParticleBatchNode : CCNode {
    void removeChildAtIndex(unsigned long arg0, boolean arg1);
    void addChild(any arg0, long arg1);
    void addChild(any arg0);
    void addChild(any arg0, long arg1, long arg2);
    void draw();
    void setTexture(CCTexture2D arg0);
    boolean initWithFile(DOMString arg0, unsigned long arg1);
    void disableParticle(unsigned long arg0);
    [CallWith=ScriptState] any getTexture();
    void visit();
    void removeAllChildrenWithCleanup(boolean arg0);
    void removeChild(any arg0, boolean arg1);
    void insertChild(any arg0, unsigned long arg1);
    boolean initWithTexture(CCTexture2D arg0, unsigned long arg1);
    void reorderChild(any arg0, long arg1);
    [CallWith=ScriptState]  static any createInternal(DOMString arg0, unsigned long arg1);
    [CallWith=ScriptState]  static any createWithTexture(CCTexture2D arg0, unsigned long arg1);
    [Custom] void ctor();
};
