// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCParallaxNode : CCNode {
    void addChild(any arg0, unsigned long arg1, long arg2);
    void addChild(any arg0, unsigned long arg1, CCPoint arg2, CCPoint arg3);
    void visit();
    void removeAllChildrenWithCleanup(boolean arg0);
    void removeChild(any arg0, boolean arg1);
    [CallWith=ScriptState]  static any createInternal();
    [Custom] void ctor();
};
