// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface CCTableViewCell : CCNode {
    void reset();
    void setIdx(unsigned long arg0);
    void setObjectID(unsigned long arg0);
    unsigned long getObjectID();
    unsigned long getIdx();
};
