// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface GUIReader : CCObject  {
    [CallWith=ScriptState] any widgetFromJsonFile(DOMString arg0);
     static void purge();
    [CallWith=ScriptState]  static any getInstance();
};
