// Copyright (c) 2014 The Chromium Authors. All rights reserved.
// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

[
    Conditional=COCOS2D,
    WillBeGarbageCollected,
    Constructor,
    NoInterfaceObject
] interface RelativeLayoutParameter : LayoutParameter {
    void setAlign(short arg0);
    void setRelativeToWidgetName(DOMString arg0);
    DOMString getRelativeName();
    DOMString getRelativeToWidgetName();
    void setRelativeName(DOMString arg0);
    short getAlign();
    [CallWith=ScriptState]  static any createInternal();
};
